pipeline {
    agent any
    tools {
            gradle 'myGradle'
    }

    triggers {
        pollSCM('*/5 * * * *')
    }

    stages {
        stage('Compile') {
            steps {
                gradle 'check'
                gradle tasks 'clean'
                }
            }
        }
    }
    post {
        failure {
            echo 'build failed'
        }
    }

}