pipeline {
    agent any
    tools {
            gradle 'myGradle'
    }

    triggers {
        pollSCM('*/5 * * * *')
    }

    stages {
        stage('Compile') {
            steps {
                gradle('check')
                gradle {
                    tasks('clean')
                    tasks('build')
                    switches('--info')
                }
            }
        }
    }
    post {
        failure {
            echo 'build failed'
        }
    }

}